services:
  lrossi-ma-thesis-db:
    image: postgres:16.9
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=db
    ports:
      - '6543:5432'
    volumes:
      - lrossi-ma-thesis-db:/var/lib/postgresql/data
    networks:
      - lrossi-ma-thesis

volumes:
  lrossi-ma-thesis-db:
    driver: local

networks:
  lrossi-ma-thesis:
