"""add_is_goal_flag_to_rule

Revision ID: 23927d737dea
Revises: 5abda0a26473
Create Date: 2025-07-23 15:23:09.296149

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '23927d737dea'
down_revision: Union[str, Sequence[str], None] = '5abda0a26473'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rules', sa.Column('is_goal', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rules', 'is_goal')
    # ### end Alembic commands ###
