"""Add agent enum

Revision ID: 4a92c9496c78
Revises: c45e7f8a9b12
Create Date: 2025-07-20 22:28:17.707077

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4a92c9496c78'
down_revision: Union[str, Sequence[str], None] = 'c45e7f8a9b12'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    banner_status = postgresql.ENUM('USER', 'AI',
                                    name='agent')
    banner_status.create(op.get_bind())

    # ### commands auto generated by Alembic - please adjust! ###

    op.execute('ALTER TABLE chat_messages ALTER COLUMN agent TYPE agent'
               ' USING agent::text::agent')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    postgresql.ENUM(name='agent').drop(op.get_bind())
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('chat_messages', 'agent',
                    existing_type=sa.Enum('USER', 'AI', name='agent'),
                    type_=sa.VARCHAR(),
                    existing_nullable=False)
    # ### end Alembic commands ###
