"""Rename name of atom db model

Revision ID: 4c947d3e8e09
Revises: 72ac0beb4e5d
Create Date: 2025-07-17 10:15:31.921536

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4c947d3e8e09'
down_revision: Union[str, Sequence[str], None] = '72ac0beb4e5d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('agentic_logs_regulation_fragment_id_fkey'), 'agentic_logs', type_='foreignkey')
    op.create_foreign_key(None, 'agentic_logs', 'regulation_fragments', ['regulation_fragment_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('atom_spans_atom_id_fkey'), 'atom_spans', type_='foreignkey')
    op.create_foreign_key(None, 'atom_spans', 'atoms', ['atom_id'], ['id'], ondelete='CASCADE')
    op.add_column('atoms', sa.Column('predicate', sa.String(), nullable=False))
    op.create_foreign_key(None, 'atoms', 'regulation_fragments', ['regulation_fragment_id'], ['id'], ondelete='CASCADE')
    op.drop_column('atoms', 'name')
    op.create_foreign_key(None, 'chat_messages', 'regulation_fragments', ['regulation_fragment_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'chat_messages', type_='foreignkey')
    op.add_column('atoms', sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'atoms', type_='foreignkey')
    op.drop_column('atoms', 'predicate')
    op.drop_constraint(None, 'atom_spans', type_='foreignkey')
    op.create_foreign_key(op.f('atom_spans_atom_id_fkey'), 'atom_spans', 'atoms', ['atom_id'], ['id'])
    op.drop_constraint(None, 'agentic_logs', type_='foreignkey')
    op.create_foreign_key(op.f('agentic_logs_regulation_fragment_id_fkey'), 'agentic_logs', 'regulation_fragments', ['regulation_fragment_id'], ['id'])
    # ### end Alembic commands ###
