"""Unify user and system prompt for logs

Revision ID: 4fefa76dee07
Revises: 4c947d3e8e09
Create Date: 2025-07-17 15:01:47.078561

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4fefa76dee07'
down_revision: Union[str, Sequence[str], None] = '4c947d3e8e09'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agentic_logs', sa.Column('user_prompt', sa.String(), nullable=False))
    op.add_column('agentic_logs', sa.Column('system_prompt', sa.String(), nullable=True))
    op.drop_column('agentic_logs', 'log_entry')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agentic_logs', sa.Column('log_entry', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('agentic_logs', 'system_prompt')
    op.drop_column('agentic_logs', 'user_prompt')
    # ### end Alembic commands ###
