"""Initial Migration

Revision ID: 72ac0beb4e5d
Revises: 
Create Date: 2025-07-16 18:13:21.250388

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '72ac0beb4e5d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('atoms',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('regulation_fragment_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('is_negated', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('chat_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('regulation_fragment_id', sa.Integer(), nullable=False),
    sa.Column('content', sa.String(), nullable=False),
    sa.Column('agent', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('regulation_fragments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('content', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('agentic_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('log_entry', sa.String(), nullable=False),
    sa.Column('message_source', sa.Enum('SYSTEM_PROMPT', 'USER_PROMPT', 'MODEL_RESPONSE', name='messagesource'), nullable=False),
    sa.Column('regulation_fragment_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['regulation_fragment_id'], ['regulation_fragments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('atom_spans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('atom_id', sa.Integer(), nullable=False),
    sa.Column('start', sa.Integer(), nullable=False),
    sa.Column('end', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['atom_id'], ['atoms.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('atom_spans')
    op.drop_table('agentic_logs')
    op.drop_table('regulation_fragments')
    op.drop_table('chat_messages')
    op.drop_table('atoms')
    # ### end Alembic commands ###
