"""add_token_fields_to_regulation_fragment

Revision ID: a8ca1755b42c
Revises: d58c172874fa
Create Date: 2025-08-12 09:34:19.565764

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a8ca1755b42c'
down_revision: Union[str, Sequence[str], None] = 'd58c172874fa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    formalism_enum = sa.Enum('PROLOG', name='formalism')
    formalism_enum.create(op.get_bind(), checkfirst=True)

    op.add_column('regulation_fragments', sa.Column('formalism', formalism_enum, nullable=False, server_default="PROLOG"))
    op.add_column('regulation_fragments', sa.Column('used_tokens_in', sa.Integer(), nullable=False, server_default="0"))
    op.add_column('regulation_fragments', sa.Column('used_tokens_out', sa.Integer(), nullable=False, server_default="0"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('regulation_fragments', 'used_tokens_out')
    op.drop_column('regulation_fragments', 'used_tokens_in')
    op.drop_column('regulation_fragments', 'formalism')

    # Drop the enum type
    sa.Enum(name='formalism').drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
