"""Add LLM identifiers

Revision ID: b131c1b6e8c9
Revises: 4fefa76dee07
Create Date: 2025-07-18 12:36:21.791171

"""
from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'b131c1b6e8c9'
down_revision: Union[str, Sequence[str], None] = '4fefa76dee07'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    banner_status = postgresql.ENUM('GPT_3_5_TURBO', 'GPT_4o_MINI', 'SONNET_4', 'GEMINI_2_5',
                                    name='llmidentifier')
    banner_status.create(op.get_bind())

    op.add_column('regulation_fragments', sa.Column('llm_identifier',
                                                    sa.Enum('GPT_3_5_TURBO', 'GPT_4o_MINI', 'SONNET_4', 'GEMINI_2_5',
                                                            name='llmidentifier'), nullable=False,
                                                    server_default='GPT_3_5_TURBO'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('regulation_fragments', 'llm_identifier')
    # ### end Alembic commands ###
