"""add_source_field_to_regulation_fragment

Revision ID: ba8e1a352893
Revises: a8ca1755b42c
Create Date: 2025-08-12 09:42:53.215938

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ba8e1a352893'
down_revision: Union[str, Sequence[str], None] = 'a8ca1755b42c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('regulation_fragments', sa.Column('source', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('regulation_fragments', 'source')
    # ### end Alembic commands ###
