"""add_is_error_flag_to_agentic_log

Revision ID: c08e348fd81d
Revises: 23927d737dea
Create Date: 2025-07-23 17:12:09.657472

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = 'c08e348fd81d'
down_revision: Union[str, Sequence[str], None] = '23927d737dea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agentic_logs', sa.Column('is_error', sa.Boolean(), nullable=False, server_default="FALSE"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('agentic_logs', 'is_error')
    # ### end Alembic commands ###
